name: "Generate demo"

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.RAPIDEZ_ACTIONS_ACCOUNT_PAT }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Fix permissions
        run: sudo chmod -R 0777 vendor/orchestra/testbench-core/laravel/

      - name: Generate demo
        run: composer generate-demo

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update demo
          file_pattern: demo/components.html
